/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import models.SO;
import models.Process;

/**
 *
 * @author jhona
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public SO sistemO;

    public MainView() {
        initComponents();
    }

    public void createSO(int timeQuantum) {
        sistemO = new SO(timeQuantum);
    }

    public void addProcess(Process proc) {
        sistemO.addProcess(proc);
    }

    public void startProcess() {
        ArrayList<Process> queue = new ArrayList<>();
        boolean aux = true;
        int timer = 0;
        int auxQuantum = sistemO.quantum;
        int auxPosition = 0;
        int quantum = 0;

        do {
            timer++;
            quantum++;
            for (Process process : sistemO.list) {
                if (process.timeArrival == timer) {
                    queue.add(process);
                }
            }
            queue.get(auxPosition).timeProcess = queue.get(auxPosition).timeProcess - 1;
            System.out.println(quantum+" -- "+auxQuantum);
            System.out.println(queue.get(auxPosition).id + " -- " + queue.get(auxPosition).timeProcess);

            
            
            if (queue.get(auxPosition).timeProcess <= 0) {
                queue.remove(queue.get(auxPosition));
                System.out.println("termino proceso");
                auxPosition++;
                if (auxPosition  >= queue.size()) {
                    auxPosition = 0;
                }
            }
            
              if (quantum == auxQuantum) {
                 
                System.out.println("se cumplio el quantum");
                auxPosition++;
                quantum = 0;
                if (auxPosition >= queue.size() ) {
                    auxPosition = 0;
                }
            }
          
            
            
            if (queue.size() == 0) {
                aux = false;
            }
        }while(aux);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
